"""Constrained MDP via Lagrangian Penalty — Section 3.5 (Enhancement).

HYPOTHESIS (stated before running):
  Adding a Lagrangian penalty for drone-depletion events will reduce
  depletion_events by ≥50% relative to IQL, while degrading
  cost_per_order by ≤10%.  The constraint budget d=1.0 depletion event
  per episode is achievable because the dataset contains many greedy
  trajectories that never deplete.

METHOD:
  We extend IQL to a Constrained MDP (CMDP) by:
  1. Learning a *cost* critic Q_c(s,a) alongside the reward critic Q_r(s,a).
  2. Adding a learnable Lagrange multiplier λ≥0.
  3. Effective Q used for policy: Q_eff = Q_r - λ·Q_c
  4. Dual update: λ ← clip(λ + α_λ·(J_c − d), 0, λ_max)
     where J_c ≈ mean batch cost, d = per-step constraint budget.

COST SIGNAL (from (obs, next_obs)):
  c_i = 1 if any drone's "alive" bit fell from obs to next_obs, else 0.
  This directly captures depletion events without needing extra env info.

ABLATION plan (see REPORT.md):
  A) λ fixed at 0     → plain IQL (no constraint)   [reuse iql.pt]
  B) λ fixed at 1.0   → constant-penalty ablation
  C) λ learned        → full Lagrangian (this file)
  The return-vs-violation trade-off curve is generated by sweeping λ_fixed ∈ {0, 0.5, 1, 2, 5}.
"""
from __future__ import annotations

import os
import copy
import argparse
from typing import Optional

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import yaml

from utils import (OBS_DIM, N_ACTIONS, flatten_obs, build_mlp,
                   OfflineBuffer, Logger, soft_update)
from iql import VNet, QNet, PolicyNet, _expectile_loss


# ─────────────────────────────────────────────────────
# CMDP training
# ─────────────────────────────────────────────────────

def train_cmdp(cfg: dict, data_path: str,
               save_path_q: str, save_path_v: str,
               save_path_pi: str, save_path_qc: str,
               log_path: str, seed: int = 0,
               lambda_fixed: Optional[float] = None):
    """
    lambda_fixed: if provided, skip the dual update and use this value.
                  Used for the ablation sweep.
    """
    torch.manual_seed(seed)
    np.random.seed(seed)

    device    = cfg.get("device", "cpu")
    lr        = cfg.get("lr", 3e-4)
    lr_lambda = cfg.get("lr_lambda", 1e-3)
    batch     = cfg.get("batch_size", 256)
    n_steps   = cfg.get("n_steps", 100_000)
    gamma     = cfg.get("gamma", 0.99)
    tau_soft  = cfg.get("tau_soft", 0.005)
    expectile = cfg.get("expectile", 0.7)
    beta      = cfg.get("beta", 3.0)
    # Constraint budget: depletion events per episode.
    # Per-step: d_per_step = d_episode / T_max
    d_episode = cfg.get("constraint_budget", 1.0)
    d_per_step = d_episode / cfg.get("T_max", 500)
    lambda_max = cfg.get("lambda_max", 10.0)
    hidden    = tuple(cfg.get("hidden", [256, 256]))
    log_freq  = cfg.get("log_freq", 1000)

    buf = OfflineBuffer(data_path, device=device)

    # Reward networks (same as IQL)
    v_net  = VNet(OBS_DIM, hidden).to(device)
    q_net  = QNet(OBS_DIM, N_ACTIONS, hidden).to(device)
    pi_net = PolicyNet(OBS_DIM, N_ACTIONS, hidden).to(device)
    q_tgt  = copy.deepcopy(q_net)

    # Cost critic Q_c(s,a): separate network for constraint value
    qc_net = QNet(OBS_DIM, N_ACTIONS, hidden).to(device)
    qc_tgt = copy.deepcopy(qc_net)

    opt_v  = optim.Adam(v_net.parameters(),  lr=lr)
    opt_q  = optim.Adam(q_net.parameters(),  lr=lr)
    opt_pi = optim.Adam(pi_net.parameters(), lr=lr)
    opt_qc = optim.Adam(qc_net.parameters(), lr=lr)

    # Lagrange multiplier (log-parameterized to ensure λ≥0)
    log_lambda = torch.tensor([np.log(max(cfg.get("lambda_init", 1.0), 1e-6))],
                              requires_grad=True, device=device)
    opt_lambda = optim.Adam([log_lambda], lr=lr_lambda)

    logger  = Logger(log_path)
    running = {"loss_q": 0.0, "loss_v": 0.0, "loss_pi": 0.0,
               "loss_qc": 0.0, "lambda": 0.0, "cost_mean": 0.0,
               "q_data": 0.0}

    for step in range(1, n_steps + 1):
        (obs_b, act_b, rew_b, nobs_b, done_b, term_b,
         cost_b) = buf.sample_with_cost(batch)

        lam = (lambda_fixed if lambda_fixed is not None
               else log_lambda.exp().item())

        # ── 1. V-network (expectile on reward Q) ─────────────────────
        with torch.no_grad():
            q_taken_sg = q_tgt(obs_b).gather(1, act_b.unsqueeze(1)).squeeze(1)
        v_pred = v_net(obs_b)
        loss_v = _expectile_loss(q_taken_sg - v_pred, expectile)
        opt_v.zero_grad(); loss_v.backward(); opt_v.step()

        # ── 2. Reward Q-network ───────────────────────────────────────
        with torch.no_grad():
            v_next = v_net(nobs_b)
            td_r   = rew_b + gamma * (1.0 - term_b) * v_next
        q_all_cur = q_net(obs_b)
        q_taken   = q_all_cur.gather(1, act_b.unsqueeze(1)).squeeze(1)
        loss_q    = 0.5 * nn.functional.mse_loss(q_taken, td_r)
        opt_q.zero_grad(); loss_q.backward(); opt_q.step()

        # ── 3. Cost Q-network ─────────────────────────────────────────
        with torch.no_grad():
            # Cost Bellman: Q_c(s,a) = c(s,a) + γ·V_c(s') ≈ c + γ·max Q_c(s')
            qc_next = qc_tgt(nobs_b).max(dim=1).values   # cost critic can use max
            td_c    = cost_b + gamma * (1.0 - term_b) * qc_next
        qc_taken = qc_net(obs_b).gather(1, act_b.unsqueeze(1)).squeeze(1)
        loss_qc  = 0.5 * nn.functional.mse_loss(qc_taken, td_c)
        opt_qc.zero_grad(); loss_qc.backward(); opt_qc.step()

        # ── 4. Policy: AWR on penalized advantage ─────────────────────
        with torch.no_grad():
            q_r   = q_tgt(obs_b).gather(1, act_b.unsqueeze(1)).squeeze(1)
            q_c   = qc_tgt(obs_b).gather(1, act_b.unsqueeze(1)).squeeze(1)
            # Penalized Q: Q_r - λ·Q_c
            q_eff = q_r - lam * q_c
            adv   = q_eff - v_pred.detach()
            weight = torch.exp(beta * adv).clamp(max=100.0)

        log_pi      = pi_net(obs_b)
        log_pi_taken = log_pi.gather(1, act_b.unsqueeze(1)).squeeze(1)
        loss_pi     = -(weight * log_pi_taken).mean()
        opt_pi.zero_grad(); loss_pi.backward(); opt_pi.step()

        # ── 5. Dual update for λ ──────────────────────────────────────
        if lambda_fixed is None:
            constraint_violation = cost_b.mean() - d_per_step
            loss_lam = -log_lambda * constraint_violation.detach()
            opt_lambda.zero_grad(); loss_lam.backward(); opt_lambda.step()
            # Project λ into [0, lambda_max]
            with torch.no_grad():
                log_lambda.clamp_(np.log(1e-6), np.log(lambda_max))

        # ── Soft updates ──────────────────────────────────────────────
        soft_update(q_tgt,  q_net,  tau_soft)
        soft_update(qc_tgt, qc_net, tau_soft)

        # ── Logging ───────────────────────────────────────────────────
        running["loss_q"]    += loss_q.item()
        running["loss_v"]    += loss_v.item()
        running["loss_pi"]   += loss_pi.item()
        running["loss_qc"]   += loss_qc.item()
        running["lambda"]    += lam
        running["cost_mean"] += cost_b.mean().item()
        running["q_data"]    += q_taken.detach().mean().item()

        if step % log_freq == 0:
            avg = {k: v / log_freq for k, v in running.items()}
            print(f"[CMDP] step {step:6d}/{n_steps}  "
                  f"L_Q={avg['loss_q']:.4f}  L_π={avg['loss_pi']:.4f}  "
                  f"λ={avg['lambda']:.3f}  cost={avg['cost_mean']:.4f}")
            logger.log(step=step, **avg)
            running = {k: 0.0 for k in running}

    logger.flush()
    for path, net in [(save_path_q, q_net), (save_path_v, v_net),
                      (save_path_pi, pi_net), (save_path_qc, qc_net)]:
        os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
        torch.save(net.state_dict(), path)
    final_lambda = (lambda_fixed if lambda_fixed is not None
                    else log_lambda.exp().item())
    print(f"[CMDP] saved. Final λ={final_lambda:.4f}")
    return CMDPPolicy(q_net, qc_net, pi_net, final_lambda, device)


# ─────────────────────────────────────────────────────
# Policy
# ─────────────────────────────────────────────────────

class CMDPPolicy:
    """Acts on penalized Q: argmax_{valid a} (Q_r - λ·Q_c)(s, a)."""

    def __init__(self, q_net: QNet, qc_net: QNet, pi_net: PolicyNet,
                 lam: float, device: str = "cpu"):
        self.q_net  = q_net.to(device).eval()
        self.qc_net = qc_net.to(device).eval()
        self.pi_net = pi_net.to(device).eval()
        self.lam    = lam
        self.device = device

    def act(self, obs: dict) -> int:
        flat = torch.tensor(flatten_obs(obs), dtype=torch.float32,
                            device=self.device).unsqueeze(0)
        with torch.no_grad():
            q_r  = self.q_net(flat).squeeze(0).cpu().numpy()
            q_c  = self.qc_net(flat).squeeze(0).cpu().numpy()
        q_eff = q_r - self.lam * q_c
        mask  = np.asarray(obs["action_mask"], dtype=bool)
        q_eff[~mask] = -np.inf
        return int(np.argmax(q_eff))

    def action_values(self, obs: dict) -> Optional[np.ndarray]:
        flat = torch.tensor(flatten_obs(obs), dtype=torch.float32,
                            device=self.device).unsqueeze(0)
        with torch.no_grad():
            q_r = self.q_net(flat).squeeze(0).cpu().numpy()
            q_c = self.qc_net(flat).squeeze(0).cpu().numpy()
        q_eff = q_r - self.lam * q_c
        mask  = np.asarray(obs["action_mask"], dtype=bool)
        q_eff[~mask] = np.nan
        return q_eff


def load_cmdp(q_path: str, v_path: str, pi_path: str, qc_path: str,
              lam: float, device: str = "cpu",
              hidden=(256, 256)) -> CMDPPolicy:
    q_net  = QNet(OBS_DIM, N_ACTIONS, hidden)
    v_net  = VNet(OBS_DIM, hidden)
    pi_net = PolicyNet(OBS_DIM, N_ACTIONS, hidden)
    qc_net = QNet(OBS_DIM, N_ACTIONS, hidden)
    q_net.load_state_dict(torch.load(q_path,  map_location=device))
    v_net.load_state_dict(torch.load(v_path,  map_location=device))
    pi_net.load_state_dict(torch.load(pi_path, map_location=device))
    qc_net.load_state_dict(torch.load(qc_path, map_location=device))
    return CMDPPolicy(q_net, qc_net, pi_net, lam, device)


# ─────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--config",   default="configs/cmdp.yaml")
    ap.add_argument("--data",     default="../drone_dispatch_env/data/D_logs.npz")
    ap.add_argument("--save-q",   default="weights/cmdp_q.pt")
    ap.add_argument("--save-v",   default="weights/cmdp_v.pt")
    ap.add_argument("--save-pi",  default="weights/cmdp_pi.pt")
    ap.add_argument("--save-qc",  default="weights/cmdp_qc.pt")
    ap.add_argument("--log",      default="logs/cmdp.csv")
    ap.add_argument("--seed",     type=int, default=0)
    ap.add_argument("--lambda-fixed", type=float, default=None,
                    help="Fix λ for ablation sweep; if None, learn it")
    args = ap.parse_args()

    with open(args.config) as f:
        cfg = yaml.safe_load(f)

    policy = train_cmdp(cfg, args.data,
                        args.save_q, args.save_v, args.save_pi, args.save_qc,
                        args.log, args.seed, args.lambda_fixed)

    import sys
    sys.path.insert(0, "../drone_dispatch_env")
    import drone_dispatch_env
    from drone_dispatch_env import evaluate, Config
    results = evaluate(policy, Config(), seeds=[0, 1, 2])
    print("\nCMDP quick eval (seeds 0-2):")
    for k, v in results["mean"].items():
        print(f"  {k}: {v:.4f}")
